export enum AppRoute {
	Home = '/',
	Search = 'search',
	About = 'about',
	AboutLaureats = 'laureates',
	AboutDocs = 'docs',
	AboutCredits = 'credits',
	Awards = 'awards',
	Fond = 'fond',
	AboutProjects = 'projects',
	AwardsGeneral = 'awards/general',
	AwardsDetails = 'awards/details',
	News = 'news',
	Videos = 'videos',
	Events = 'events',
	Belyaev = 'belyaev',
}
